In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])
print(arr.shape)
print(arr)

(4,)
[1 2 3 4]


In [7]:
arr_reshape = arr.reshape(1,4)
print(arr_reshape)

[[1 2 3 4]]


### Broadcasting when multiply two numpy

In [20]:
arr_1 = np.array([1,2,3,4])
print(arr_1)
print(arr_1.shape)
print()
arr_1 =arr_1.reshape(-1)
print(arr_1)
print(arr_1.shape)

[1 2 3 4]
(4,)

[1 2 3 4]
(4,)


In [23]:
arr_2 = np.random.randint(2,20,20)
print(arr_2)
print(arr_2.shape)
print()
arr_2 = arr_2.reshape(5,-1)
print(arr_2)
print(arr_2.shape)

[12 10 12 18 14  9 13 11  2 11 19 12  4 15  3 11  5 12  3  8]
(20,)

[[12 10 12 18]
 [14  9 13 11]
 [ 2 11 19 12]
 [ 4 15  3 11]
 [ 5 12  3  8]]
(5, 4)


In [25]:
mul =  arr_2 * arr_1
print(mul.shape)
print(mul)

(5, 4)
[[12 20 36 72]
 [14 18 39 44]
 [ 2 22 57 48]
 [ 4 30  9 44]
 [ 5 24  9 32]]


### Dot Product with two ndarray

In [28]:
arr_1 = np.array([1,2,3,4]).reshape(2,-1)
print(arr_1)
print(arr_1.shape)

[[1 2]
 [3 4]]
(2, 2)


In [29]:
arr_2 = np.array([1,2,3,4,5,6]).reshape(2,-1)
print(arr_2)
print(arr_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [32]:
np.dot(arr_1,arr_2)

array([[ 9, 12, 15],
       [19, 26, 33]])

### Minimum and Maximum between two ndarray

In [38]:
arr_1 = np.array([-1,2,3,4]).reshape(2,-1)
print(arr_1)
print(arr_1.shape)

arr_2 = np.array([6,3,9,3]).reshape(2,-1)
print(arr_2)
print(arr_2.shape)
print('-------------')
print(np.maximum(arr_1,arr_2))

[[-1  2]
 [ 3  4]]
(2, 2)
[[6 3]
 [9 3]]
(2, 2)
-------------
[[6 3]
 [9 4]]


### Max and min of ndarray

In [53]:
arr_1 = np.array([-1,2,3,4]).reshape(2,-1)
print(arr_1)
print(arr_1.shape)

[[-1  2]
 [ 3  4]]
(2, 2)


In [62]:
print(np.max(arr_1, axis=0, keepdims=True))
print(np.max(arr_1, axis=0, keepdims=False))

[[3 4]]
[3 4]


In [61]:
print(np.min(arr_1, axis=1, keepdims=True))
print(np.min(arr_1, axis=1, keepdims=False))

[[-1]
 [ 3]]
[-1  3]


### sum of ndarray

In [63]:
arr_1 = np.array([-1,2,3,4]).reshape(2,-1)
print(arr_1)
print(arr_1.shape)

[[-1  2]
 [ 3  4]]
(2, 2)


In [65]:
print(np.sum(arr_1, axis=0,keepdims=True))
print(np.sum(arr_1, axis=0,keepdims=False))

[[2 6]]
[2 6]


In [66]:
print(np.sum(arr_1, axis=1,keepdims=True))
print(np.sum(arr_1, axis=1,keepdims=False))

[[1]
 [7]]
[1 7]


### Numpy repeat and title

In [70]:
arr = np.array([-1,2,3,4]).reshape(2,-1)
print(arr)
print(arr.shape)

[[-1  2]
 [ 3  4]]
(2, 2)


In [78]:
arr_1 = np.repeat(arr,2, axis=1)
print(arr_1)
print(arr_1.shape)

[[-1 -1  2  2]
 [ 3  3  4  4]]
(2, 4)


In [79]:
arr_1 = np.repeat(arr,2, axis=0)
print(arr_1)
print(arr_1.shape)

[[-1  2]
 [-1  2]
 [ 3  4]
 [ 3  4]]
(4, 2)


In [80]:
arr_1 = np.tile(arr,2)
print(arr_1)
print(arr_1.shape)

[[-1  2 -1  2]
 [ 3  4  3  4]]
(2, 4)


### Boolen array

In [82]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [85]:
print(arr >=2)
print(arr[arr>=2])
print((arr[arr>=2]).shape)

[[False  True  True]
 [ True  True  True]]
[2 3 4 5 6]
(5,)


### np.where condition

In [86]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [90]:
indicating = np.where(arr >=2)
print(indicating)
print(indicating[0].shape)

(array([0, 0, 1, 1, 1], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))
(5,)


In [92]:
print(arr[indicating])

[2 3 4 5 6]
